name: Build
on:
  workflow_dispatch:
jobs:
  build-to-dockerhub:
    runs-on: ubuntu-22.04
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug
    permissions:
      contents: read
    outputs:
      image_tag: ${{ steps.extract-tag.outputs.image_tag }} # Expose image tag to next job
    steps:
      - name: Kaniko build and push
        id: extract-tag
        run: |
          IMAGE_TAG="$(echo ${GITHUB_SHA} | head -c 7)-$GITHUB_RUN_NUMBER"
          cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "$(echo -n "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_PASSWORD }}" | base64 )"
              }
            }
          }
          EOF
          # Build and push image with Kaniko
          /kaniko/executor --dockerfile="./Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
            --destination="$DOCKER_IMAGE_NAME:$IMAGE_TAG" \
            --push-retry 5

          # Store image tag in step output for next job
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

        env:
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_IMAGE_NAME: "ayushj0909/flask"

  update-repo-variable:
    runs-on: ubuntu-22.04
    needs: build-to-dockerhub  # Ensure it runs after the first job
    steps:
      - name: Update Repository Variable with Image Tag
        run: |
          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/variables/LATEST_IMAGE_TAG \
               -d '{"value": "'"${{ needs.build-to-dockerhub.outputs.image_tag }}"'"}'
